name: Test & Deploy

on: 
  pull_request:
    branches:
      - main 

jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
        name: Install dependencies
        run: npm install
      - name: Test utils
        run: npm run utils.test

  test-app:
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_news_test
          postgresql user: mr_testymctest
          postgresql password: pa55word
      - name: Install dependencies
        run: npm install
      - name: Test app
        uses: PGDATABASE=nc_news_test PGUSER=mr_testymctest PGPASSWORD=pa55word npm test