name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello from the pipeline! Sure is dark in here...'

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test utils
        run: npm run test-utils

  test-app:
    needs: test-utils
    runs-on: ubunti-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: mr_tiahtest
          postgresql password: pa55word
      - name: Install dependencies
        run: npm install
      - name: Test app
        uses: PGDATABASE=test_db PGUSER=mr_tiahtest PGPASSWORD=pa55word npm test
